### ISSUE TITLE
Add progress bar for audio snippet

### ISSUE THREAD

**Issue by outoflaksh** [outoflaksh/Spotanew#4]
Currently, there's no indication of the song's progress as the audio sample is playing. Therefore, a minimalistic progress bar that tracks the progress of the played audio can be added at the bottom of the song cover.

**Comment by manav-06** [comment]
Hi @outoflaksh , you can assign this to me

**Comment by outoflaksh** [comment]
Hi @manav-06 the feature has been added via a recent pull request, so i’ll be closing this issue. Thanks!
